---
title: "appli cocoapp"
output: html_notebook
---

#Libraries
```{r}
library(pdftools)
library(tabulizer)
library(dplyr)
library(stringr)
library(progress)
```

#import cocoa
```{r}
cocoa<-pdf_text("../cocoa19.pdf")
```

#a faire plus tard pour le tableaux de cancero
```{r}
# cocoa_tab<-extract_tables("C:/Users/ouazzak/Documents/PMSI/cocoa.pdf", encoding="UTF-8")
```

```{r}
cocoadf<-data.frame(page=numeric(),txt=character())
pb <- progress_bar$new(
format = " Page :page / :total :what [:bar] :percent eta: :eta",
clear = FALSE, total = length(cocoa), width = 60)

for (i in 1:length(cocoa)){
  add<-data.frame(page=i,txt=gsub("\\r\\n",' ',x=cocoa[i], perl=T))
  cocoadf<-rbind(cocoadf,add)
  pb$tick(tokens=list(what="Progression :", page=i, total=length(cocoa)))
  Sys.sleep(1/100)
  
}
``` 

#import cim10
```{r}
cim10<-read.table('LIBCIM10MULTI_mod.TXT', sep="|", dec='!', stringsAsFactors = FALSE, encoding="Latin-1", col.names = c("code","severite","auto","severite2","lib","nom"), quote="")

```

#stringr traitement
```{r}
test<-as.character(cocoadf[200,2])
pattern<-'(?<=.)(?=[A-Z]{1}[0-9]{2}(\\.|\\ )[0-9]*(\\ )+)'
patterntest<-'(?<=\\ )(?=[A-Z]{1}[0-9]{2}(\\.|\\ )[0-9]*((\\ ){2,}|(\\ †)))'

splittest<-strsplit(test,patterntest,perl=TRUE)
splittest[[1]]

for (i in 2:length(splittest[[1]])){
    print(splittest[[1]][i])
}

pattern2<-"(?<=[0-9])(?=((\\ ){8,}))"
fulltextcode<-splitted_txt[[1]][2]
templist<-strsplit(fulltextcode,pattern2,perl=TRUE)

pattern3<-"A l'excusion de"
templist<-strsplit(fulltextcode,pattern2,perl=TRUE)

```


#traitement full doc
```{r}
splitcocoa<-list()
pattern<-'(?<=\\ )(?=[A-Z]{1}[0-9]{2}(\\.|\\ )[0-9]*((\\ ){2,}|(\\ †)))'
pattern2<-'(?<=[A-Z]{1}[0-9]{2}(\\.|\\ )[0-9]*((\\ ){2,}|(\\ †)))(?=(\\ ){8,})'

pb <- progress_bar$new(
format = " Row :row / :total :what [:bar] :percent eta: :eta",
clear = FALSE, total = nrow(cocoadf), width = 60)

for (i in 1:nrow(cocoadf)){
  txt<-as.character(cocoadf[i,2])
  
  splitted_txt<-strsplit(txt,pattern,perl=TRUE)
  
  for (i in 2:length(splitted_txt[[1]])){
    
    fulltextcode<-splitted_txt[[1]][i]
    templist<-strsplit(fulltextcode,pattern2,perl=TRUE)
    
  }
  
  splitcocoa<-append(splitcocoa,splitted_txt)
  pb$tick(tokens=list(what="Progression :", row=i, total=nrow(cocoa)))
  Sys.sleep(1/10000)
  
}

```

#all the first split
```{r}
for (i in 1:length(splitcocoa)){
  cat('\n\nFirst : ',splitcocoa[[i]][2])
}

```



```{r}
splitcocoa[[1]]

#seulement les character commencant par code CIM10
reg<-'[A-Z]{1}[0-9]{2}\\.[1-9]+( ){2,}'
grep(reg,splitcocoa[[200]])
```

